server {
  listen 3000 default_server;
  server_name _;
  root /php/var;

  location / {
    index index.php;
    try_files $uri $uri/ index.php = 404;
  }

  location ~* \.php$ {
    try_files $uri $uri/ index.php = 404;
    include fastcgi_params;
    fastcgi_pass  127.0.0.1:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME /php/var$fastcgi_script_name;
    fastcgi_param QUERY_STRING    $query_string;
    fastcgi_param REQUEST_METHOD  $request_method;
    fastcgi_param CONTENT_TYPE    $content_type;
    fastcgi_param CONTENT_LENGTH  $content_length;
  }

  location /ping {
    return 200;
  }
}